[[plugins]]
package = "netlify-plugin-ghost-markdown"

  [plugins.inputs]
  # Required: Your Ghost domain, must not end in a trailing slash
  ghostURL = "https://www.robertoserrano.pro"

  # Required: Content API key from the Integrations screen in Ghost Admin
  ghostKey = "ae9c98bb2b77b4c8ea1e901014"

  # Optional: Directory containing image assets (assets/images by default)
  assetsDir = "./assets/images/"

  # Optional: Directory containing pages (site root by default)
  pagesDir = "./"

  # Optional: Directory containing posts (_posts/ directory by default)
  postsDir = "./blog/"

  # Optional: Layout value for pages (page by default)
  # pageLayout = "page"

  # Optional: Layout value for posts (post by default)
  postsLayout = "blog"

  # Optional: Date prefix on post file names (true by default)
  postDatePrefix = true

  # Optional: File path and name for a timestamp caching file (_data/ghostMarkdownCache.json by default)
  cacheFile = "./_data/ghostMarkdownCache.json"