[[plugins]]
package = "netlify-plugin-ghost-markdown"

  [plugins.inputs]
  # Required: Your Ghost domain, must not end in a trailing slash
  ghostURL = "https://www.robertoserrano.pro"

  # Required: Content API key from the Integrations screen in Ghost Admin
  ghostKey = "ae9c98bb2b77b4c8ea1e901014"
